import { ANIME5E } from "./module/config.js";

class Anime5eSkills {
    static MODULE_NAME = "Anime-5e";
    static MODULE_TITLE = "Anime 5e";

	static init = async () => {
            CONFIG.DND5E.skills.aca = { label: "ANIME5E.SkillAca", ability: "int", /*toString: () => { return "Academia"; }*/ fullKey: "academia", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.pFJrqz2pqcA39Fc7", icon: "" };
            CONFIG.DND5E.skills.agr = { label: "ANIME5E.SkillAgr", ability: "wis", /*toString: () => { return "Agriculture"; }*/ fullKey: "agriculture", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.onqDkpb4uTwf7hu8", icon: "" };
            CONFIG.DND5E.skills.alc = { label: "ANIME5E.SkillAlc", ability: "int", /*toString: () => { return "Alchemy"; }*/ fullKey: "alchemy", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.uoBjiSYrNdvu7LRw", icon: "" };
            CONFIG.DND5E.skills.arch = { label: "ANIME5E.SkillArch", ability: "int", /*toString: () => { return "Architecture"; }*/ fullKey: "architecture", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.W896wxRlTrxBDXBb", icon: "" };
            CONFIG.DND5E.skills.akn = { label: "ANIME5E.SkillAkn", ability: "int", /*toString: () => { return "Area Knowledge"; }*/ fullKey: "areaKnowledge", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.3uwZpak8CNDYyLVE", icon: "" };
            CONFIG.DND5E.skills.art = { label: "ANIME5E.SkillArt", ability: "dex", /*toString: () => { return "Artisan"; }*/ fullKey: "artisan", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.KiuZIOFYHGswPKEj", icon: "" };
            CONFIG.DND5E.skills.bus = { label: "ANIME5E.SkillBus", ability: "int", /*toString: () => { return "Business"; }*/ fullKey: "business", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.WymUpl371SQkfFDR", icon: "" };
            CONFIG.DND5E.skills.clm = { label: "ANIME5E.SkillClm", ability: "dex", /*toString: () => { return "Climbing"; }*/ fullKey: "climbing", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.DbqgTtLFc9WVEE4O", icon: "" };
            CONFIG.DND5E.skills.ctb = { label: "ANIME5E.SkillCtb", ability: "con", /*toString: () => { return "Controlled Breathing"; }*/ fullKey: "controlledBreathing", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.O9t9hwZaO3I8zun1", icon: "" };
            CONFIG.DND5E.skills.cul = { label: "ANIME5E.SkillCul", ability: "int", /*toString: () => { return "Culture"; }*/ fullKey: "culture", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.6TfIUYen4h7k70Tz", icon: "" };
            CONFIG.DND5E.skills.dis = { label: "ANIME5E.SkillDis", ability: "cha", /*toString: () => { return "Disguise"; }*/ fullKey: "disguise", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.lQShIJKhv84UzZ5q", icon: "" };
            CONFIG.DND5E.skills.dma = { label: "ANIME5E.SkillDma", ability: "wis", /*toString: () => { return "Domestic Arts"; }*/ fullKey: "domesticArts", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.4dhn4kbF2iA3azr9", icon: "" };
            CONFIG.DND5E.skills.emp = { label: "ANIME5E.SkillEmp", ability: "cha", /*toString: () => { return "Empathy"; }*/ fullKey: "empathy", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.fJ2eOk6ha5x3ufho", icon: "" };
            CONFIG.DND5E.skills.eng = { label: "ANIME5E.SkillEng", ability: "int", /*toString: () => { return "Engineering"; }*/ fullKey: "engineering", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.JMJ7HvrR2T24Js4W", icon: "" };
            CONFIG.DND5E.skills.eti = { label: "ANIME5E.SkillEti", ability: "cha", /*toString: () => { return "Etiquette"; }*/ fullKey: "etiquette", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.YnnQDv5Z8pH37jXW", icon: "" };
            CONFIG.DND5E.skills.foc = { label: "ANIME5E.SkillFoc", ability: "wis", /*toString: () => { return "Focus"; }*/ fullKey: "focus", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.FsJ9T922f89bo8Cf", icon: "" };
            CONFIG.DND5E.skills.frg = { label: "ANIME5E.SkillFrg", ability: "dex", /*toString: () => { return "Forgery"; }*/ fullKey: "forgery", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.fdPkbqEnIx9qQBQ9", icon: "" };
            CONFIG.DND5E.skills.gam = { label: "ANIME5E.SkillGam", ability: "wis", /*toString: () => { return "Gaming"; }*/ fullKey: "gaming", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.zgYy35MtAP3PQBII", icon: "" };
            CONFIG.DND5E.skills.hlm = { label: "ANIME5E.SkillHlm", ability: "dex", /*toString: () => { return "Helming"; }*/ fullKey: "helming", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.cExFC04QibdTpbeT", icon: "" };
            CONFIG.DND5E.skills.intg = { label: "ANIME5E.SkillIntg", ability: "wis", /*toString: () => { return "Interrogation"; }*/ fullKey: "interrogation", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.0wIcxNC2dkVu1e4S", icon: "" };
            CONFIG.DND5E.skills.law = { label: "ANIME5E.SkillLaw", ability: "int", /*toString: () => { return "Law"; }*/ fullKey: "law", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.Dre5E3woBUIeLL2H", icon: "" };
            CONFIG.DND5E.skills.ldr = { label: "ANIME5E.SkillLdr", ability: "cha", /*toString: () => { return "Leadership"; }*/ fullKey: "leadership", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.nLGuSYNd6QdAOmTm", icon: "" };
            CONFIG.DND5E.skills.mng = { label: "ANIME5E.SkillMin", ability: "int", /*toString: () => { return "Mining"; }*/ fullKey: "mining", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.b2czYsH1wJ6ts0Wy", icon: "" };
            CONFIG.DND5E.skills.nav = { label: "ANIME5E.SkillNav", ability: "int", /*toString: () => { return "Navigation"; }*/ fullKey: "navigation", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.dLZhou5cadVCBqJJ", icon: "" };
            CONFIG.DND5E.skills.phy = { label: "ANIME5E.SkillPhy", ability: "int", /*toString: () => { return "Physics"; }*/ fullKey: "physics", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.OwBN1CfU9eF53f1V", icon: "" };
            CONFIG.DND5E.skills.rid = { label: "ANIME5E.SkillRid", ability: "dex", /*toString: () => { return "Riding"; }*/ fullKey: "riding", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.XSSJnme84KkyCzaN", icon: "" };
            CONFIG.DND5E.skills.sed = { label: "ANIME5E.SkillSed", ability: "cha", /*toString: () => { return "Seduction"; }*/ fullKey: "seduction", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.WSajwKyxBBZfryoz", icon: "" };
            CONFIG.DND5E.skills.str = { label: "ANIME5E.SkillStr", ability: "cha", /*toString: () => { return "Street Sense"; }*/ fullKey: "streetSense", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.vC1rPkJkUMPTtVYB", icon: "" };
            CONFIG.DND5E.skills.swm = { label: "ANIME5E.SkillSwm", ability: "con", /*toString: () => { return "Swimming"; }*/ fullKey: "swimming", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.BIo1z04kAmJgvTHj", icon: "" };
            CONFIG.DND5E.skills.trp = { label: "ANIME5E.SkillTrp", ability: "dex", /*toString: () => { return "Traps"; }*/ fullKey: "traps", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.yYQtrl84SnlOqDC5", icon: "" };
            CONFIG.DND5E.skills.vis = { label: "ANIME5E.SkillVis", ability: "wis", /*toString: () => { return "Visual Arts"; }*/ fullKey: "visualArts", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.I5YRDkPCqTfcETcp", icon: "" };
            CONFIG.DND5E.skills.war = { label: "ANIME5E.SkillWar", ability: "wis", /*toString: () => { return "Warfare"; }*/ fullKey: "warfare", reference: "Compendium.Anime-5e.attribute-subsets.JournalEntry.Wx9oxIFsZXZXQ7iT.JournalEntryPage.hShttGvHsMutK6Ug", icon: "" };

		CONFIG.DND5E.sourceBooks.A5E = "Anime 5E";
    }
}

Hooks.once("init", Anime5eSkills.init);
