export const ANIME5E = {};

ANIME5E.skills = {
    aca: { label: "ANIME5E.SkillAca", ability: "int", fullKey:"academics" },
    agr: { label: "ANIME5E.SkillAgr", ability: "wis", fullKey:"agriculture" },
    alc: { label: "ANIME5E.SkillAlc", ability: "int", fullKey:"alchemy" },
    arch: { label: "ANIME5E.SkillArch", ability: "int", fullKey:"architecture" },
    akn: { label: "ANIME5E.SkillAkn", ability: "int", fullKey:"areaKnowledge" },
    art: { label: "ANIME5E.SkillArt", ability: "dex", fullKey:"artisan" },
    bus: { label: "ANIME5E.SkillBus", ability: "int", fullKey:"business" },
    clm: { label: "ANIME5E.SkillClm", ability: "dex", fullKey:"climbing" },
    ctb: { label: "ANIME5E.SkillCtb", ability: "con", fullKey:"controlledBreathing" },
    cul: { label: "ANIME5E.SkillCul", ability: "int", fullKey:"culture" },
    dis: { label: "ANIME5E.SkillDis", ability: "cha", fullKey:"disguise" },
    dma: { label: "ANIME5E.SkillDma", ability: "wis", fullKey:"domesticArts" },
    emp: { label: "ANIME5E.SkillEmp", ability: "cha", fullKey:"empathy" },
    eng: { label: "ANIME5E.SkillEng", ability: "int", fullKey:"engineering" },
    eti: { label: "ANIME5E.SkillEti", ability: "cha", fullKey:"etiquette" },
    foc: { label: "ANIME5E.SkillFoc", ability: "wis", fullKey:"focus" },
    frg: { label: "ANIME5E.SkillFrg", ability: "dex", fullKey:"forgery" },
    gam: { label: "ANIME5E.SkillGam", ability: "wis", fullKey:"gaming" },
    hlm: { label: "ANIME5E.SkillHlm", ability: "dex", fullKey:"helming" },
    intg: { label: "ANIME5E.SkillIntg", ability: "wis", fullKey:"interrogation" },
    law: { label: "ANIME5E.SkillLaw", ability: "int", fullKey:"law" },
    ldr: { label: "ANIME5E.SkillLdr", ability: "cha", fullKey:"leadership" },
    min: { label: "ANIME5E.SkillMin", ability: "int", fullKey:"mining" },
    nav: { label: "ANIME5E.SkillNav", ability: "int", fullKey:"navigation" },
    phy: { label: "ANIME5E.SkillPhy", ability: "int", fullKey:"physics" },
    rid: { label: "ANIME5E.SkillRid", ability: "dex", fullKey:"riding" },
    sed: { label: "ANIME5E.SkillSed", ability: "cha", fullKey:"seduction" },
    str: { label: "ANIME5E.SkillStr", ability: "cha", fullKey:"streetSense" },
    swm: { label: "ANIME5E.SkillSwm", ability: "con", fullKey:"swimming" },
    trp: { label: "ANIME5E.SkillTrp", ability: "dex", fullKey:"traps" },
    vis: { label: "ANIME5E.SkillVis", ability: "wis", fullKey:"visualArts" },
    war: { label: "ANIME5E.SkillWar", ability: "wis", fullKey:"warfare" }
}